# File: chat/consumers.py

import json
from channels.generic.websocket import AsyncWebsocketConsumer
from channels.db import database_sync_to_async
from django.utils import timezone
from .models import ChatRoom, Message


class ChatConsumer(AsyncWebsocketConsumer):


    async def connect(self):


        self.user = self.scope['user']

        # Reject unauthenticated connections immediately.
        # close() sends a WebSocket close frame to the browser
        # and ends the connection. We never accept it first —
        # accepting and then closing is a two-step handshake
        # that sends unnecessary data. Closing before accepting
        # rejects the connection outright.
        if not self.user.is_authenticated:
            await self.close()
            return
            # return is essential here — without it Python
            # would continue executing the rest of connect()
            # even after closing the connection.

        # Extract the room_name from the URL.
        # This comes from the URLRouter pattern:
        # ws/chat/<str:room_name>/
        # If the browser connects to ws://localhost/ws/chat/establishment_1/
        # then self.room_name = 'establishment_1'
        self.room_name = self.scope['url_route']['kwargs']['room_name']

        # The channel group name is what Redis uses to identify
        # this room's subscriber list. We use the room_name
        # directly — it's already unique per room.
        # All consumers for the same room share this group name.
        self.group_name = self.room_name

        # Fetch the ChatRoom object from the database.
        # We use our helper method below which wraps the
        # synchronous ORM call for async context.
        self.room = await self.get_room(self.room_name)

        # If the room doesn't exist or is inactive, reject.
        if self.room is None or not self.room.is_active:
            await self.close()
            return

        # Join the Redis channel group for this room.
        # channel_layer is the Redis connection provided by
        # Channels. group_add adds this consumer's unique
        # channel name to the named group.
        # self.channel_name is auto-generated by Channels —
        # a unique identifier for this specific consumer instance.
        await self.channel_layer.group_add(
            self.group_name,
            self.channel_name,
        )

        # Accept the WebSocket connection.
        # Until accept() is called, the connection is in a
        # pending state. The browser is waiting.
        # We do all our validation BEFORE accepting so we
        # can reject invalid connections cleanly.
        await self.accept()

        # Send message history to this newly connected user.
        # Only this user receives this — we call self.send()
        # directly, not group_send() through Redis.
        # group_send() would broadcast to everyone, which
        # would spam existing users with history they
        # already have.
        history = await self.get_message_history()
        for message in history:
            await self.send(text_data=json.dumps({
                'type': 'chat_message',
                'message': message['content'],
                'username': message['username'],
                'timestamp': message['timestamp'],
                'is_history': True,
                # is_history flag tells the browser JavaScript
                # to render these differently — no animation,
                # no "new message" sound, just silent population
                # of the chat history above the input.
            }))

    # ==========================================================
    # DISCONNECT
    # Called when the WebSocket connection closes.
    # This happens when: tab is closed, browser navigates away,
    # network drops, server closes the connection.
    # ==========================================================

    async def disconnect(self, close_code):
        # close_code is a WebSocket status code integer.
        # 1000 = normal closure, 1001 = going away (tab closed),
        # 1006 = abnormal closure (network drop).
        # We don't use it here but it's useful for debugging.

        # Leave the Redis channel group.
        # After this, this consumer will no longer receive
        # messages broadcast to the group.
        # group_discard is safe to call even if we never
        # successfully joined — it's a no-op if the
        # channel isn't in the group.
        if hasattr(self, 'group_name'):
            # hasattr check is important — if connect() failed
            # before setting self.group_name (e.g. unauthenticated
            # user), disconnect() would crash trying to access
            # an attribute that was never set.
            await self.channel_layer.group_discard(
                self.group_name,
                self.channel_name,
            )

    # ==========================================================
    # RECEIVE
    # Called when the browser sends a message over the WebSocket.
    # text_data is a JSON string sent from the browser.
    # ==========================================================

    async def receive(self, text_data):

        # Parse the incoming JSON string into a Python dict.
        try:
            data = json.loads(text_data)
        except json.JSONDecodeError:
            # Malformed JSON — ignore silently.
            # In production you might log this.
            return

        # Extract the message text.
        message_text = data.get('message', '').strip()

        # Validate — don't save or broadcast empty messages.
        if not message_text:
            return

        # Enforce a maximum message length.
        # 500 characters is generous for chat but prevents
        # someone sending a 50,000 character message that
        # floods everyone's screen.
        if len(message_text) > 500:
            message_text = message_text[:500]

        # Save the message to the database.
        # This is the synchronous ORM call wrapped for async.
        # After this line, the message exists in PostgreSQL.
        message = await self.save_message(self.user, self.room, message_text)

        # Broadcast the message to the Redis channel group.
        # group_send delivers the event dict to every consumer
        # in the group — including this consumer itself.
        # This means the sender also receives their own message
        # through the same pipeline as everyone else.
        # This is correct — it confirms to the sender that
        # their message was received and processed.
        await self.channel_layer.group_send(
            self.group_name,
            {
                'type': 'chat_message',
                # 'type' tells Channels which method to call
                # on each receiving consumer.
                # 'chat_message' maps to the chat_message()
                # method below. Channels replaces dots with
                # underscores, so 'chat.message' would also
                # map to chat_message(). We use underscores
                # directly for clarity.

                'message': message_text,
                'username': self.user.username,
                'timestamp': message.timestamp.strftime('%H:%M'),
                # strftime formats the datetime as "14:32"
                # We format server-side so all users see the
                # same timestamp format regardless of their
                # browser or locale settings.
                'is_history': False,
            }
        )

    # ==========================================================
    # CHAT_MESSAGE
    # Called on every consumer in the group when group_send
    # is called with type='chat_message'.
    # event is the dict passed to group_send above.
    # ==========================================================

    async def chat_message(self, event):
        # Send the message data to this consumer's browser
        # as a JSON string over the WebSocket.
        # self.send() sends only to THIS browser —
        # the one connected to this specific consumer instance.
        await self.send(text_data=json.dumps({
            'type': 'chat_message',
            'message': event['message'],
            'username': event['username'],
            'timestamp': event['timestamp'],
            'is_history': event['is_history'],
        }))

    # ==========================================================
    # DATABASE HELPERS
    # Synchronous ORM operations wrapped with
    # database_sync_to_async for use in async context.
    # ==========================================================

    @database_sync_to_async
    def get_room(self, room_name):
        try:
            return ChatRoom.objects.select_related('establishment').get(
                room_name=room_name,
            )
        except ChatRoom.DoesNotExist:
            return None
        # Returns None if room not found.
        # connect() checks for None and closes the connection.

    @database_sync_to_async
    def get_message_history(self):
        # Fetch the last 50 messages for this room.
        # Ordered by timestamp ascending (oldest first)
        # because that's how the model's Meta.ordering
        # is set — and it's what we want for display.
        # 50 is a reasonable history window — enough context
        # without sending a huge payload to every new joiner.
        messages = (
            Message.objects
            .filter(room=self.room)
            .select_related('user')
            .order_by('timestamp')
            [:50]
        )
        # We build a plain list of dicts here rather than
        # returning ORM objects. This is important —
        # ORM objects cannot be safely used outside the
        # database_sync_to_async context they were created in.
        # Plain dicts are just data — safe to use anywhere.
        return [
            {
                'content': msg.content,
                'username': msg.user.username if msg.user else 'Deleted User',
                'timestamp': msg.timestamp.strftime('%H:%M'),
            }
            for msg in messages
        ]

    @database_sync_to_async
    def save_message(self, user, room, content):
        return Message.objects.create(
            room=room,
            user=user,
            content=content,
        )
        # Returns the created Message instance.
        # We use message.timestamp in receive() above
        # to get the exact server-set timestamp for
        # broadcasting to the group.